spring.application.name=moonlight-maintenance

# MySQL Database Configuration
spring.datasource.url=jdbc:mysql://host.docker.internal:3306/moonlight_mnt_db
spring.datasource.username=root
spring.datasource.password=mySQL#0017

# Hibernate / JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# MySQL Dialect
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# Server Port
server.port=8080